name: flutter_admin_template
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.6
  flutter_layout_grid: ^2.0.5
  pluto_grid: ^7.0.2
  go_router: ^12.1.1
  url_launcher: ^6.2.1
  adaptive_navigation: ^0.0.9
  url_strategy: ^0.2.0
  #动画
  flutter_animate: ^4.2.0+1
  flutter_svg: ^2.0.9
  #状态管理
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.6
  riverpod_annotation: ^2.3.1

  #网络请求
  retrofit: ^4.0.3
  dio: ^5.3.3
  logger: ^2.0.2+1
  equatable: ^2.0.5
  flutter_smart_dialog: ^4.9.5+1
  ityu_tools:
    git: https://gitee.com/andoridityu/ityu_tools.git
  google_fonts: ^6.1.0
  flex_color_scheme: ^7.3.1
  awesome_dialog: ^3.1.0
  pointer_interceptor: ^0.9.3+7
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  go_router_builder: ^2.3.4


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/svg/
  fonts:
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC.otf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
